# cmd: conda build . -c conda-forge
package:
    name: autoio-base
    version: "0.9.0"

source:
    path: .

requirements:
    host:
        - conda-forge::python=3.9
    run:
        - conda-forge::python=3.9
        - conda-forge::numpy=1.21.2
        - conda-forge::scipy=1.7.1
        - conda-forge::pyyaml
        - conda-forge::mako
        - conda-forge::pytest
        - conda-forge::pytest-cov
        - conda-forge::future
        - conda-forge::flake8
        - conda-forge::pylint
