name: elstruct-env

channels:
    - pacchem
    - psi4/label/dev
    - rdkit
    - openbabel
    - conda-forge

dependencies:
    - python
    - numpy
    - pyyaml
    - mako
    - pytest
    - pytest-cov
    - future
    - flake8
    - pylint
    - rdkit::rdkit
    - openbabel::openbabel
    - psi4=1.4a1.dev102+9fd6758=py36h2de08a4_0
    - pacchem::autoparse
    - pacchem::autochem
    - conda-forge::qcelemental
