name: elstruct-env

channels:
    - defaults
    - kevinmooreiii
    - psi4
    - rdkit
    - openbabel
    - conda-forge

dependencies:
    - python=3.7
    - numpy
    - scipy
    - pyyaml
    - mako
    - pytest
    - pytest-cov
    - future
    - flake8
    - pylint
    - rdkit::rdkit
    - openbabel::openbabel
    - conda-forge::qcelemental
    - psi4::psi4
    - kevinmooreiii::autoparse
    - kevinmooreiii::automol
