# cmd: conda build . -c auto-mech -c psi4 -c rdkit -c openbabel -c conda-forge
package:
    name: autorun
    version: "0.1.3"

source:
    path: .

requirements:
    build:
        - python=3.7
    run:
        - gfortran_linux-64  # [linux]
        - python=3.7
        - numpy
        - scipy
        - pyyaml
        - mako
        - matplotlib
        - pytest
        - pytest-cov
        - future
        - flake8
        - pylint
        - auto-mech::automol
        - auto-mech::autoparse
        - auto-mech::autoio
        - auto-mech::elstruct
        - auto-mech::autofile
        - auto-mech::x2z
        - psi4::psi4
        - rdkit::rdkit
        - openbabel::openbabel
        - conda-forge::qcelemental
        - auto-mech::mess
        - auto-mech::projrot
        - auto-mech::pac99
        - auto-mech::thermp
