# cmd: conda build . -c auto-mech -c psi4 -c rdkit -c openbabel -c conda-forge
package:
    name: autorun
    version: "0.1.0"

source:
    path: .

requirements:
    build:
        - python=3.7
    run:
        - python=3.7
        - numpy
        - scipy
        - pyyaml
        - mako
        - pytest
        - pytest-cov
        - future
        - flake8
        - pylint
        - rdkit::rdkit
        - openbabel::openbabel
        - conda-forge::qcelemental
        - psi4::psi4
        - auto-mech::autoio
        - auto-mech::autoparse
        - auto-mech::automol
        - auto-mech::x2z
