version: 2
jobs:
    build-debian:
        docker:
            - image: continuumio/miniconda3
        working_directory: ~/autoio     
        steps:
            - checkout  # checkout the code
            - run: 
                name: Create conda environment
                command: |
                    apt-get update --yes
                    apt-get install --yes libxrender-dev build-essential
                    conda env create -f environment.yml
            - run:
                name: Build/install autoio
                command: |
                    source activate autoio-env
                    python setup.py install
            - run:
                name: Test chemkin_io
                command: |
                    source activate autoio-env
                    pytest -v --disable-pytest-warnings
                    flake8 --exit-zero chemkin_io
                    pylint --rcfile=../.pylintrc chemkin_io
            - run:
                name: Test mess_io
                command: |
                    source activate autoio-env
                    pytest -v --disable-pytest-warnings
                    flake8 --exit-zero mess_io
                    pylint --rcfile=../.pylintrc mess_io
            - run:
                name: Test projrot_io
                command: |
                    source activate autoio-env
                    pytest -v --disable-pytest-warnings
                    flake8 --exit-zero projrot_io
                    pylint --rcfile=../.pylintrc projrot_io
            - run:
                name: Test thermp_io
                command: |
                    source activate autoio-env
                    pytest -v --disable-pytest-warnings
                    flake8 --exit-zero thermp_io
                    pylint --rcfile=../.pylintrc thermp_io
            - run:
                name: Test varecof_io
                command: |
                    source activate autoio-env
                    pytest -v --disable-pytest-warnings
                    flake8 --exit-zero varecof_io
                    pylint --rcfile=../.pylintrc varecof_io
            - run:
                name: Test autoread
                command: |
                    source activate automol-env
                    pytest -v --cov=autoread --pyargs autoread
                    flake8 --exit-zero autoread
                    pylint --rcfile=../.pylintrc autoread
            - run:
                name: Test autowrite
                command: |
                    source activate automol-env
                    flake8 --exit-zero autowrite
                    pylint --rcfile=../.pylintrc autoread
        working_directory: ~/autoparse     
        steps:
            - checkout  # checkout the code
            - run: 
                name: Create conda environment
                command: |
                    apt-get update --yes
                    apt-get install --yes libxrender-dev build-essential
                    conda env create -f environment.yml
            - run:
                name: Build/install autoparse
                command: |
                    source activate autoparse-env
                    python setup.py install
            - run:
                name: Test autoparse
                command: |
                    source activate autoparse-env
                    cd autoparse
                    pytest -v --disable-pytest-warnings --cov=autoparse --pyargs autoparse
                    flake8 --exit-zero autoparse
                    pylint --rcfile=../.pylintrc autoparse
        working_directory: ~/elstruct
        steps:
            - checkout  # checkout the code
            - run: 
                name: Create conda environment
                command: |
                    apt-get update --yes
                    apt-get install --yes libxrender-dev build-essential
                    conda env create -f environment.yml
            - run:
                name: Test elstruct
                command: |
                    source activate elstruct-env
                    # temporary fix
                    conda install -c conda-forge pylint>=2.3
                    # temporary fix
                    python setup.py install
                    cd tests
                    pytest -v --cov=elstruct .
workflows:
    version: 2
    build-all:
        jobs:
            - build-debian
