version: 2
jobs:
    build-debian:
        docker:
            - image: continuumio/miniconda3
        steps:
            - checkout  # checkout the code
            - run: 
                name: Create conda environment
                command: |
                    conda env create -f environment.yml
            - run:
                name: Run tests
                command: |
                    source activate autoparse-env
                    python setup.py install
                    cd autoparse
                    pytest -v --cov=autoparse --pyargs autoparse
                    flake8 --exit-zero autommol
                    pylint autoparse
workflows:
    version: 2
    build-all:
        jobs:
            - build-debian
