version: 2
jobs:
    build-debian1:
        docker:
            - image: continuumio/miniconda3
        working_directory: ~/autoio     
        steps:
            - checkout  # checkout the code
            - run: 
                name: Create conda environment
                command: |
                    apt-get update --yes
                    apt-get install --yes libxrender-dev build-essential
                    conda env create -f autoio/environment.yml
            - run:
                name: Build/install autoio
                command: |
                    source activate autoio-env
                    cd autoio
                    python setup.py install
            - run:
                name: Test chemkin_io
                command: |
                    cd autoio/chemkin_io
                    source activate autoio-env
                    pytest . -v --disable-pytest-warnings --cov=chemkin_io --pyargs chemkin_io
                    flake8 --exit-zero ../chemkin_io
                    pylint --rcfile=../../.pylintrc chemkin_io
            - run:
                name: Test mess_io
                command: |
                    cd autoio/mess_io
                    source activate autoio-env
                    pytest . -v --disable-pytest-warnings --cov=mess_io --pyargs mess_io
                    flake8 --exit-zero ../mess_io
                    pylint --rcfile=../../.pylintrc mess_io
            - run:
                name: Test projrot_io
                command: |
                    cd autoio/projrot_io
                    source activate autoio-env
                    pytest . -v --disable-pytest-warnings --cov=projrot_io --pyargs projrot_io
                    flake8 --exit-zero ../projrot_io
                    pylint --rcfile=../../.pylintrc projrot_io
            - run:
                name: Test thermp_io
                command: |
                    cd autoio/thermp_io
                    source activate autoio-env
                    pytest . -v --disable-pytest-warnings --cov=thermp_io --pyargs thermp_io
                    flake8 --exit-zero ../thermp_io
                    pylint --rcfile=../../.pylintrc thermp_io
            - run:
                name: Test varecof_io
                command: |
                    cd autoio/varecof_io
                    source activate autoio-env
                    pytest . -v --disable-pytest-warnings --cov=varecof_io --pyargs varecof_io
                    flake8 --exit-zero ../varecof_io
                    pylint --rcfile=../../.pylintrc varecof_io
            - run:
                name: Test autoread
                command: |
                    cd autoio/autoread
                    source activate autoio-env
                    pytest . -v --disable-pytest-warnings --cov=autoread --pyargs autoread
                    flake8 --exit-zero ../autoread
                    pylint --rcfile-../../.pylintrc autoread
            - run:
                name: Test autowrite
                command: |
                    cd autoio/autowrite
                    source activate autoio-env
                    pytest . -v --disable-pytest-warnings --cov=autowrite --pyargs autowrite
                    flake8 --exit-zero ../autowrite
                    pylint --rcfile=../../.pylintrc autowrite
    build-debian2:
        docker:
            - image: continuumio/miniconda3
        working_directory: ~/autoparse     
        steps:
            - checkout  # checkout the code
            - run: 
                name: Create conda environment
                command: |
                    apt-get update --yes
                    apt-get install --yes libxrender-dev build-essential
                    conda env create -f autoparse/environment.yml
            - run:
                name: Build/install autoparse
                command: |
                    source activate autoparse-env
                    cd autoparse
                    python setup.py install
            - run:
                name: Test autoparse
                command: |
                    source activate autoparse-env
                    cd autoparse/autoparse
                    pytest -v --disable-pytest-warnings --cov=autoparse  --pyargs autoparse
                    flake8 --exit-zero ../../autoparse
                    pylint --rcfile=../../.pylintrc autoparse
    build-debian3:
        docker:
            - image: continuumio/miniconda3
        working_directory: ~/autorun
        steps:
            - checkout  # checkout the code
            - run: 
                name: Create conda environment
                command: |
                    apt-get update --yes
                    apt-get install --yes libxrender-dev build-essential
                    conda env create -f autorun/environment.yml
            - run:
                name: Build/install autorun
                command: |
                    source activate autorun-env
                    cd autorun
                    python setup.py install
                    cd ~
            - run:
                name: Test autorun
                command: |
                    source activate autorun-env
                    cd autorun/autorun
                    pytest -v --disable-pytest-warnings --cov=autorun --pyargs autorun
                    flake8 --exit-zero ../../autorun
                    pylint --rcfile=../../.pylintrc autorun
    build-debian4:
        docker:
            - image: continuumio/miniconda3
        working_directory: ~/elstruct
        steps:
            - checkout  # checkout the code
            - run: 
                name: Create conda environment
                command: |
                    apt-get update --yes
                    apt-get install --yes libxrender-dev build-essential
                    conda env create -f elstruct/environment.yml
            - run:
                name: Test elstruct
                command: |
                    source activate elstruct-env
                    # temporary fix
                    conda install -c conda-forge pylint>=2.3
                    # temporary fix
                    cd elstruct
                    python setup.py install
                    cd elstruct
                    pytest -v --cov=elstruct .
                    flake8 --exit-zero ../../elstruct
                    pylint --rcfile=../../.pylintrc elstruct
workflows:
    version: 2
    build-all:
        jobs:
            - build-debian1
            - build-debian2
            - build-debian3
            - build-debian4
