version: 2
jobs:
    build-debian:
        docker:
            - image: continuumio/miniconda3
        steps:
            - checkout  # checkout the code
            - run: 
                name: Create conda environment
                command: |
                    conda env create -f environment.yml
            - run:
                name: Run tests
                command: |
                    source activate autostring-env
                    # temporary fix
                    conda install -c conda-forge pylint>=2.3
                    # temporary fix
                    python setup.py install
                    cd autoparse
workflows:
    version: 2
    build-all:
        jobs:
            - build-debian
