version: 2
jobs:
    build-debian:
        docker:
            - image: continuumio/miniconda3
        steps:
            - checkout  # checkout the code
            - run: 
                name: Create conda environment
                command: |
                    apt-get update --yes
                    apt-get install --yes libxrender-dev  # needed for rdkit
                    conda env create -f environment.yml
            - run:
                name: Test elstruct
                command: |
                    source activate elstruct-env
                    # temporary fix
                    conda install -c conda-forge pylint>=2.3
                    # temporary fix
                    python setup.py install
                    cd tests
                    pytest -v --cov=elstruct .
workflows:
    version: 2
    build-all:
        jobs:
            - build-debian
