# cmd: conda build . -c auto-mech -c psi4 -c rdkit -c openbabel -c conda-forge
package:
    name: elstruct
    version: "0.2.1"

source:
    path: .

requirements:
    build:
        - python
    run:
        - python
        - numpy
        - scipy
        - pyyaml
        - mako
        - pytest
        - pytest-cov
        - future
        - flake8
        - pylint
        - rdkit::rdkit
        - openbabel::openbabel
        - conda-forge::qcelemental
        - psi4::psi4
        - auto-mech::autoparse
        - auto-mech::autorun
        - auto-mech::automol
        - auto-mech::x2z
