# cmd: conda build .
package:
    name: autoparse
    version: "0.2.1"

source:
    path: .

requirements:
    build:
        - python=3.7
    run:
        - python=3.7
        - pytest
        - pytest-cov
        - flake8
        - pylint
