# cmd: conda build .  -c auto-mech -c psi4 -c rdkit -c openbabel -c conda-forge
package:
    name: autoio
    version: "0.1.1"

source:
    path: .

requirements:
    host:
        - python=3.7
    run:
        - python=3.7
        - {{ compiler('fortran') }}
        - numpy
        - scipy
        - pyyaml
        - mako
        - matplotlib
        - pytest
        - pytest-cov
        - future
        - flake8
        - pylint
        - rdkit::rdkit
        - openbabel::openbabel
        - conda-forge::qcelemental
        - psi4::psi4
        - auto-mech::autoparse
        - auto-mech::automol
        - auto-mech::elstruct
        - auto-mech::autorun
        - auto-mech::x2z
